apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-rrir
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/rhtap-demo-afla-tenant/rhtap-demo-app/hacbs-test-project-rrir@sha256:4009e2782578fea5f5d2b70dc25efc026bae6340164bca1b06f4ac0a33335cb8
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
